#ifndef _EVENTS_H_
#define _EVENTS_H_

wxDECLARE_EVENT(DAT_SPR_LOADED, wxCommandEvent);
wxDECLARE_EVENT(DAT_SPR_SAVED, wxCommandEvent);
wxDECLARE_EVENT(RME_RES_GENERATED, wxCommandEvent);
wxDECLARE_EVENT(ADV_ATTRS_CHANGED, wxCommandEvent);
wxDECLARE_EVENT(SPRITES_CLEANED_UP, wxCommandEvent);
wxDECLARE_EVENT(PREFERENCES_SAVED, wxCommandEvent);
wxDECLARE_EVENT(AUTOBACKUP_PROCESSED, wxCommandEvent);

#endif // _EVENTS_H_
